### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by manojselvin** [Treinetic/ImageArtist#13]
Image background color is pink, its not getting transparent

**Comment by imalhasaranga** [comment]
can you provide the sample code and the images you used, for further investigation.

**Comment by manojselvin** [comment]
[image: Inline image 1]

**Comment by imalhasaranga** [comment]
image is not attached, I need following 

1. code you wrote
2. output image you received

**Comment by imalhasaranga** [comment]
closing due to less info
