### ISSUE TITLE
 imagesx() expects parameter 1 to be resource

### ISSUE THREAD

**Issue by BrainFeeder** [Treinetic/ImageArtist#16]
Hi, I'm getting this error:

    Message: imagesx() expects parameter 1 to be resource, boolean given

    Filename: lib/Image.php

    Line Number: 52

And it also throws a `Fatal error: Call to undefined function Treinetic\ImageArtist\lib\Shapes\imagecrop()` 

Did I do something wrong maybe? :p

**Comment by BrainFeeder** [comment]
apparantly I had a version of php where this function did not exist yet. Added some own version awaiting server admin to upgrade.. 

    if(!function_exists('imagecrop')) {
	function imagecrop($src, array $rect) {
        $dest = imagecreatetruecolor($rect['width'], $rect['height']);
        imagecopy(
            $dest,
            $src,
            0,
            0,
            $rect['x'],
            $rect['y'],
            $rect['width'],
            $rect['height']
        );

        return $dest;
    }
    }

**Comment by antondias** [comment]
imagecrop function needs php 5.5.0 or + version.So please upgrade your php version.

**Comment by imalhasaranga** [comment]
closing this as resolved
